name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Installing NPM packages
        run: npm ci

      - name: Building project
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
          BRANCH: gh-pages
          FOLDER: build
