name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

env:
  REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY }}
  REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN }}
  REACT_APP_DATABASE_URL: ${{ secrets.REACT_APP_DATABASE_URL }}
  REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID }}
  REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET }}
  REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }} |
    echo "test"
    echo ${{ secrets.REACT_APP_MESSAGING_SENDER_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Installing NPM packages
        run: npm ci

      - name: Building project
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN_KEY }}
          BRANCH: gh-pages
          FOLDER: ./build
